(self.AMP=self.AMP||[]).push({n:"amp-list",v:"1530320824316",f:(function(AMP){function h(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}function k(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var l=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;self.log=self.log||{user:null,dev:null,userForEmbed:null};var m=self.log;function n(){if(!m.user)throw Error("failed to call initLogConstructor");return m.user};var p=self.AMP_CONFIG||{},q=("string"==typeof p.cdnProxyRegex?new RegExp(p.cdnProxyRegex):p.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function r(a){this.K=a;this.w=this.F=0;this.o=Object.create(null)}r.prototype.has=function(a){return!!this.o[a]};r.prototype.get=function(a){var b=this.o[a];if(b)return b.access=++this.w,b.payload};
r.prototype.put=function(a,b){this.has(a)||this.F++;this.o[a]={payload:b,access:this.w};if(!(this.F<=this.K)){if(m.dev)a=m.dev;else throw Error("failed to call initLogConstructor");a.warn("lru-cache","Trimming LRU cache");a=this.o;var c=this.w+1,d,e;for(e in a){var f=a[e].access;f<c&&(c=f,d=e)}void 0!==d&&(delete a[d],this.F--)}};var t={c:!0,v:!0,a:!0,ad:!0},u,v,w=/[?&]amp_js[^&]*/,x=/[?&]amp_gsa[^&]*/,y=/[?&]amp_r[^&]*/,z=/[?&]usqp[^&]*/;
function A(a){var b;u||(u=self.document.createElement("a"),v=self.UrlCache||(self.UrlCache=new r(100)));var c=b?null:v,d=u;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=
d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;c&&c.put(a,e);a=e}return a}function B(a){"string"==typeof a&&(a=A(a));var b;(b="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,b=a.length-10,b=0<=b&&a.indexOf(".localhost",b)==b);return b}
function C(a,b){var c;c=void 0===c?"source":c;n().assert(null!=a,"%s %s must be available",b,c);var d=a;n().assert(B(d)||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d);return d}
function D(a){"string"==typeof a&&(a=A(a));var b=a;"string"==typeof b&&(b=A(b));if(!q.test(b.origin))return a.href;var b=a.pathname.split("/"),c=b[1];n().assert(t[c],"Unknown path prefix in url %s",a.href);var d=b[2],e="s"==d?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(d);n().assert(0<e.indexOf("."),"Expected a . in origin %s",e);b.splice(1,"s"==d?3:2);b=e+b.join("/");c=(c=a.search)&&"?"!=c?(c=c.replace(w,"").replace(x,"").replace(y,"").replace(z,"").replace(/^[?&]/,""))?"?"+
c:"":"";return b+c+(a.hash||"")};function F(a){var b="fast-amp-list",c;if(a.__AMP__EXPERIMENT_TOGGLES)c=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);c=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var d in a.AMP_CONFIG){var e=a.AMP_CONFIG[d];"number"===typeof e&&0<=e&&1>=e&&(c[d]=Math.random()<e)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(d=a.AMP_CONFIG["allow-doc-opt-in"],e=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(var e=
e.getAttribute("content").split(","),f=0;f<e.length;f++)-1!=d.indexOf(e[f])&&(c[e[f]]=!0);Object.assign(c,G(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){d=a.AMP_CONFIG["allow-url-opt-in"];e=a.location.originalHash||a.location.hash;a=Object.create(null);if(e)for(var g;g=l.exec(e);)f=k(g[1],g[1]),g=g[2]?k(g[2],g[2]):"",a[f]=g;for(e=0;e<d.length;e++)f=a["e-"+d[e]],"1"==f&&(c[d[e]]=!0),"0"==f&&(c[d[e]]=!1)}}var E=c;return!!E[b]}
function G(a){a:{var b;try{b=a.document.cookie}catch(E){b=""}if(a=b)for(a=a.split(";"),b=0;b<a.length;b++){var c=a[b].trim(),d=c.indexOf("="),e;if(e=-1!=d)e=c.substring(0,d).trim(),e="AMP_EXP"==k(e,void 0);if(e){a=c.substring(d+1).trim();a=k(a,a);break a}}a=null}var f=a,g=f?f.split(/\s*,\s*/g):[];a=Object.create(null);for(b=0;b<g.length;b++)0!=g[b].length&&("-"==g[b][0]?a[g[b].substr(1)]=!1:a[g[b]]=!0);return a};function H(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function I(a,b,c){if(a.nodeType){var d=(a.ownerDocument||a).defaultView;if(d=d!=(d.__AMP_TOP||d)&&J(d,b)?K(d,b):null)return d}!a.nodeType||c?(c=L(a),c=M(c),b=K(c,b)):b=null;return b}function N(a,b){a=a.__AMP_TOP||a;return K(a,b)}function L(a){return a.nodeType?N((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function M(a){a=L(a);return a.isSingleDoc()?a.win:a}
function K(a,b){J(a,b);var c=O(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function P(a){var b=Q(a);if(b)return b;var c=new H,d=c,e=d.promise,d=d.resolve;O(a).bind={obj:null,promise:e,resolve:d,context:null,ctor:null};return e}function Q(a){var b=O(a).bind;if(b){if(b.promise)return b.promise;K(a,"bind");return b.promise=Promise.resolve(b.obj)}return null}function O(a){var b=a.services;b||(b=a.services={});return b}
function J(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function aa(a,b,c){if(b(a))c();else{var d=a.ownerDocument.defaultView;if(d.MutationObserver){var e=new d.MutationObserver(function(){b(a)&&(e.disconnect(),c())});e.observe(a,{childList:!0})}else var f=d.setInterval(function(){b(a)&&(d.clearInterval(f),c())},5)}}function ba(a,b){aa(a.documentElement,function(){return!!a.body},b)}function ca(a){return new Promise(function(b){ba(a,b)})}function R(a){for(;a.firstChild;)a.removeChild(a.firstChild)};function da(a){var b=L(a),c=Q(M(a));return c?c:b.whenBodyAvailable().then(function(){return S(b.win,b.getHeadNode())}).then(function(){var c=b.win;return c.ampExtendedElements&&c.ampExtendedElements["amp-bind"]?P(M(a)):null})}function T(a){var b=I(a,"bind");return b?Promise.resolve(b):a.nodeType?(b=(a.ownerDocument||a).defaultView,b!==(b.__AMP_TOP||b)?ea(b):da(a)):Promise.resolve(null)}
function S(a,b){var c;if(b){c=[];b=b.querySelectorAll("script[custom-element]");for(var d=0;d<b.length;d++)c.push(b[d].getAttribute("custom-element"))}else c=[];if(!c.includes("amp-bind"))return Promise.resolve();var e=N(a,"extensions");return e.waitForExtension(a,"amp-bind")}function ea(a){return ca(a.document).then(function(){return S(a,a.document.head)}).then(function(){return a.ampExtendedElements&&a.ampExtendedElements["amp-bind"]?P(a):null})};function fa(a){var b={bubbles:!0},c={detail:null};Object.assign(c,b);if("function"==typeof a.CustomEvent)return new a.CustomEvent("amp:dom-update",c);a=a.document.createEvent("CustomEvent");a.initCustomEvent("amp:dom-update",!!c.bubbles,!!c.cancelable,null);return a};function U(a,b,c){var d=this;this.I=N(a,"timer");this.M=b;this.L=c||0;this.l=-1;this.C=0;this.D=!1;this.J=function(){d.l=-1;d.C=0;d.D=!0;d.M();d.D=!1}}U.prototype.isPending=function(){return-1!=this.l};U.prototype.schedule=function(a){var b=a||this.L;this.D&&10>b&&(b=10);var c=Date.now()+b;return!this.isPending()||-10>c-this.C?(this.cancel(),this.C=c,this.l=this.I.delay(this.J,b),!0):!1};U.prototype.cancel=function(){this.isPending()&&(this.I.cancel(this.l),this.l=-1)};function ga(a,b,c,d){c=void 0===c?".":c;d=void 0===d?0:d;var e=C(b.getAttribute("src"),b),f=I(a,"url-replace",!0),g=1<=d?f.expandUrlAsync(e):Promise.resolve(e);return g.then(function(c){if(1==d){var e=f.collectUnwhitelistedVarsSync(b);if(0<e.length)throw n().createError("URL variable substitutions in CORS fetches from dynamic URLs (e.g. via amp-bind) require opt-in. "+('Please add data-amp-replace="'+e.join(" ")+'" to the ')+("<"+b.tagName+"> element. See https://bit.ly/amp-var-subs."));}var g={};
b.hasAttribute("credentials")?g.credentials=b.getAttribute("credentials"):g.requireAmpResponseSourceOrigin=!1;return N(a.win,"batched-xhr").fetchJson(c,g)}).then(function(a){return a.json()}).then(function(a){if(null==a)throw Error("Response is undefined.");var b;b=c||".";if("."!=b){b=b.split(".");for(var d=0;d<b.length;d++){var e=b[d];if(e&&a&&void 0!==a[e]&&(null==a||"object"!=typeof a?0:Object.prototype.hasOwnProperty.call(a,e)))a=a[e];else{a=void 0;break}}}b=a;return b})};function V(a){var b;b=AMP.BaseElement.call(this,a)||this;b.h=null;b.A=!1;b.H=new U(b.win,function(){return ha(b)});b.j=null;b.N=N(b.win,"templates");b.B=!1;b.G=null;b.m=null;b.registerAction("refresh",function(){b.B&&W(b)},100);return b}h(V,AMP.BaseElement);V.prototype.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a||"fluid"==a||"intrinsic"==a};
V.prototype.buildCallback=function(){var a=this;this.G=this.element.getAttribute("src");this.h=this.win.document.createElement("div");this.applyFillContent(this.h,!0);this.element.appendChild(this.h);this.h.hasAttribute("role")||this.h.setAttribute("role","list");this.element.hasAttribute("aria-live")||this.element.setAttribute("aria-live","polite");T(this.element).then(function(b){a.m=b})};V.prototype.reconstructWhenReparented=function(){return!1};
V.prototype.layoutCallback=function(){this.B=!0;return W(this)};V.prototype.mutatedAttributesCallback=function(a){var b=a.src,c=a.state;if(void 0!==b){var d=typeof b;if("string"===d)this.B&&W(this);else if("object"===d){var e=Array.isArray(b)?b:[b];X(this,e);this.element.setAttribute("src","")}else this.user().error("amp-list",'Unexpected "src" type: '+b)}else void 0!==c&&(b=Array.isArray(c)?c:[c],X(this,b),n().error("amp-list","[state] is deprecated, please use [src] instead."))};
V.prototype.isLoadingReused=function(){return this.element.hasAttribute("reset-on-refresh")};function Y(a,b){b?a.getVsync().mutate(function(){a.toggleFallback(!0);a.A=!0}):a.A&&a.getVsync().mutate(function(){a.toggleFallback(!1);a.A=!1})}
function W(a){if(!a.element.getAttribute("src"))return Promise.resolve();a.element.hasAttribute("reset-on-refresh")&&(a.togglePlaceholder(!0),a.toggleLoading(!0,a.isLoadingReused()),Y(a,!1),R(a.h));var b=a.element.getAttribute("items")||"items";return ia(a,b).then(function(c){a.element.hasAttribute("single-item")&&(n().assert("undefined"!==typeof c,'Response must contain an array or object at "%s". %s',b,a.element),Array.isArray(c)||(c=[c]));n().assert(Array.isArray(c),'Response must contain an array at "%s". %s',
b,a.element);var d=parseInt(a.element.getAttribute("max-items"),10);d<c.length&&(c=c.slice(0,d));return X(a,c)},function(a){throw n().createError("Error fetching amp-list",a);}).then(function(){a.getFallback()&&Y(a,!1);a.togglePlaceholder(!1);a.toggleLoading(!1)},function(b){a.toggleLoading(!1);if(a.getFallback())Y(a,!0),a.togglePlaceholder(!1);else throw b;})}function X(a,b){var c=new H,d=c.promise,e=c.resolve,f=c.reject;a.j||a.H.schedule();a.j={items:b,resolver:e,rejecter:f};return d}
function ha(a){function b(){a.j!==c?a.H.schedule(1):a.j=null}var c=a.j;a.N.findAndRenderTemplateArray(a.element,c.items).then(function(b){return ja(a,b)}).then(function(b){return ka(a,b)}).then(function(){b();c.resolver()},function(){b();c.rejecter()})}function ja(a,b){return F(a.win)?a.m&&a.m.signals().get("FIRST_MUTATE")?Z(a,a.m,b):Promise.resolve(b):T(a.element).then(function(c){return c?Z(a,c,b):Promise.resolve(b)})}
function Z(a,b,c){function d(){return c}return b.scanAndApply(c,[a.h]).then(d,d)}function ka(a,b){R(a.h);b.forEach(function(b){b.hasAttribute("role")||b.setAttribute("role","listitem");a.h.appendChild(b)});b=fa(a.win);a.h.dispatchEvent(b);a.getVsync().measure(function(){var b=a.h.scrollHeight;b>a.element.offsetHeight&&a.attemptChangeHeight(b).catch(function(){})})}
function ia(a,b){var c=a.getAmpDoc(),d=a.element.getAttribute("src"),e=1;if(d==a.G||A(D(d)).origin==A(D(c.win.location)).origin)e=2;return ga(c,a.element,b,e)}(function(a){a.registerElement("amp-list",V)})(self.AMP);
})});
//# sourceMappingURL=amp-list-0.1.js.map

